### PR TITLE
Fix typo in ember-oauth2.js

### PR DESCRIPTION
**Pull request by mphasize**
If a "scope" is defined, Ember would fail with `Assertion Failed: Cannot call `Ember.get` with an empty string`, due to the `get('.scope')` call. This should fix it.

### CODE REVIEW

**Comment by alexgaribay** [comment]
I'm running into this issue. Can this get merged?

**Comment by amkirwan** [comment]
looks good thanks

**Comment by miguelcobain** [comment]
Can we get this released, please?
This fix isn't published on npm.

**Comment by amkirwan** [comment]
@miguelcobain whoops :( I'll release it to npm tonight

**Pull request merged**
